AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31

Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members
  CodeDeployRole:
    Type: String
    Description: IAM role to allow AWS CodeDeploy to manage deployment of AWS Lambda functions
  Stage:
    Type: String
    Description: The name for a project pipeline stage, such as Staging or Prod, for which resources are provisioned and deployed.
    Default: ''

Globals:
  Function:
    AutoPublishAlias: live
    DeploymentPreference:
      Enabled: true
      Type: Canary10Percent5Minutes
      Role:
        Ref: CodeDeployRole

Resources:
  dev:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: dev
      Description: Development Stage
      RestApiId: !Ref MyRestApi
      DeploymentId: !Ref TestDeployment
      Variables:
        Stack: dev
  HelloWorldServiceApi:
    Type: 'AWS::Serverless::Function'
    Properties:
      MemorySize: 3008
      Timeout: 60
      Handler: com.aws.codepipeline.test.StreamLambdaHandler::handleRequest
      Runtime: java8
      Role: !GetAtt
        - LambdaExecutionRole
        - Arn
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
      #CodeUri: s3://aws-codebuild-java-aws-lambda-hello-world-developer/e8e08175b9f86a21f7d567b292e8db4f

  LambdaExecutionRole:
    Description: Creating service role in IAM for AWS Lambda
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub '${ProjectId}-Execution${Stage}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      PermissionsBoundary: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/${ProjectId}_PermissionsBoundary'